// export const metadata = {
//   title: 'My Next.js App',
//   description: 'Welcome to my Next.js app!',
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <header>
//           <h1>My App</h1>
//           <nav>
//             <a href="/">Home</a>
//             <a href="/about">About</a>
//           </nav>
//         </header>
//         <main>{children}</main>
//         <footer>
//           <p>&copy; 2024 My App</p>
//         </footer>
//       </body>
//     </html>
//   );
// }
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "../components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#F5F7F8" }}
      >
        {/* Wrapping content inside the StoreProvider */}
        <StoreProvider>
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
